GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5cdbc94c72017d027979d308

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Saitama",
    "subscribedToChannel": "One Punch Man"
}

###
DELETE http://localhost:3000/subscribers/5cdbc94c72017d027979d308

###
PATCH  http://localhost:3000/subscribers/5cdbd252cc87b6075febe634
Content-Type: application/json

{
    "name": "Ray"
}